### ISSUE TITLE
really off beat

### ISSUE THREAD

**Issue by Dizzyiou** [lukew3/stemPlayerOnline#4]
im not sure if this is a problem with the actual website, or just the songs, but the stems are all really out of sync with each other

**Comment by Dizzyiou** [comment]
issue is only with pre-set tracks and not custom added, still a problem, but not as big of a deal as i thought

**Comment by lukew3** [comment]
Should be fixed now

**Comment by Dizzyiou** [comment]
seems to work perfectly now, thank you!
