### ISSUE TITLE
when i pause it i cannot unpause

### ISSUE THREAD

**Issue by Dizzyiou** [lukew3/stemPlayerOnline#6]
also it doesnt seem looping is working, as whenever i try and loop it just kind of like isolates a random part of the song and doesnt loop, i think its like mistaking the loop menu for the regular menu.

**Comment by Dizzyiou** [comment]
so, new discovery, it only wont let me unpause after i try and loop the track

**Comment by lukew3** [comment]
Looping is still in progress so I'm still working out some bugs, but I'm not sure I am having your issue. The interface has changed since you used it last to be more similar to the yeezy player, so I'm not sure if your issue still exists. Does the issue still occur on the current version?

**Comment by Dizzyiou** [comment]
it's all fixed now, thank you! also amazing work 👍
