### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Dizzyiou** [lukew3/stemPlayerOnline#7]
Hey! I recommend making it so the color you choose saves, and also a feature for splitting music (https://github.com/danielfrg/demucs-app)

**Comment by Dizzyiou** [comment]
also, maybe a discord for development updates, not really that big of a deal, but if you feel like it, you should

**Comment by lukew3** [comment]
Thanks for the feedback! I implemented the saving colors feature, so your selected colors should persist between refreshes now. I don't want to get into paying a bunch of money for hosting stem splitting software or anything right now so unless there's some sort of free api for splitting stems, I don't think that that feature will be implemented. Even then, it may be out of scope. 

Here's a discord I just made: https://discord.gg/jfnFhggJGZ. I'll probably set up an automated channel for site updates soon. How do you think I should show links to the discord and github on the site? Maybe text links in the top right or icons in the bottom right?

**Comment by Dizzyiou** [comment]
maybe like just a basic hyperlink in the top left would work
